name: Deploy Reflex App to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install Reflex
        run: |
          python -m pip install --upgrade pip
          pip install reflex==0.8.2

      - name: Build project
        run: reflex export

      - name: Unzip frontend.zip
        run: unzip .web/frontend.zip -d public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
